//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mobike.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class boleta
    {
        public int id_boleta { get; set; }
        public System.DateTime fecha { get; set; }
        public string id_personaF { get; set; }
        public string id_biciF { get; set; }
        public int id_recorridoF { get; set; }
    
        public virtual bicicleta bicicleta { get; set; }
        public virtual usuario usuario { get; set; }
        public virtual recorrido recorrido { get; set; }
    }
}
