//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mobike.Datos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MoBikeEntities : DbContext
    {
        public MoBikeEntities()
            : base("name=MoBikeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<administrador> administrador { get; set; }
        public virtual DbSet<bicicleta> bicicleta { get; set; }
        public virtual DbSet<boleta> boleta { get; set; }
        public virtual DbSet<comuna> comuna { get; set; }
        public virtual DbSet<estacionamiento> estacionamiento { get; set; }
        public virtual DbSet<recorrido> recorrido { get; set; }
        public virtual DbSet<usuario> usuario { get; set; }
    }
}
