//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mobike.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class recorrido
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public recorrido()
        {
            this.boleta = new HashSet<boleta>();
        }
    
        public int id_recorrido { get; set; }
        public double kilometros { get; set; }
        public System.DateTime inicio_recorrido { get; set; }
        public System.DateTime fin_recorrido { get; set; }
        public double tiempo_estimado { get; set; }
        public double cobro { get; set; }
        public string id_personaF { get; set; }
        public string correoF { get; set; }
        public string id_biciF { get; set; }
    
        public virtual bicicleta bicicleta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<boleta> boleta { get; set; }
        public virtual usuario usuario { get; set; }
    }
}
